from main.views.GetProdutoDisponivelView  import buscar_produtos_disponiveis, buscar_produto
from main.views.GetProdutoAgricultorView import buscar_produtos_agricultor
from main.views.PostProdutoView  import cadastrar_produto
from main.views.DeleteProdutoView  import deletar_produto
from main.views.patchAtualizarProdutoView import atualizar_produto
