# Generated by Django 3.2.9 on 2024-11-02 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtoWebserver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='foto',
            field=models.ImageField(max_length=500, upload_to='produto'),
        ),
    ]
